/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtlCliente;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author nicolasgarcia
 */
public class FrmRegistro extends javax.swing.JFrame {

    /**
     * Creates new form FrmRegistro
     */
    CtlCliente ctlCliente;

    public FrmRegistro() {
        initComponents();
        ctlCliente = new CtlCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        txtPoblacionCliente = new javax.swing.JTextField();
        txtTelefonoCliente = new javax.swing.JTextField();
        txtMovilCliente = new javax.swing.JTextField();
        txtemailCliente = new javax.swing.JTextField();
        txtObservacionCliente = new javax.swing.JTextField();
        cbSexoCliente = new javax.swing.JComboBox<>();
        cbEstadocivil = new javax.swing.JComboBox<>();
        rbtnSiDesempleado = new javax.swing.JRadioButton();
        jdcFechaNacimientoCliente = new com.toedter.calendar.JDateChooser();
        rbtnNoDesempleado = new javax.swing.JRadioButton();
        rbtnSiFumador = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        rbtnNoFumador = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtAliasCliente = new javax.swing.JTextField();
        txtapellidoCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txtnombreCliente = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtDireccionCliente = new javax.swing.JTextField();
        ChckEditarCliente = new javax.swing.JCheckBox();
        btnGuardarCliente = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel8.setBackground(new java.awt.Color(245, 245, 245));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtPoblacionCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtTelefonoCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtMovilCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtemailCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtObservacionCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        cbSexoCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        cbEstadocivil.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbEstadocivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        rbtnSiDesempleado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rbtnSiDesempleado.setText("Si");

        jdcFechaNacimientoCliente.setDateFormatString("yyyy-MM-d");
        jdcFechaNacimientoCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        rbtnNoDesempleado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rbtnNoDesempleado.setText("No");

        rbtnSiFumador.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rbtnSiFumador.setText("Si");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Movil");

        rbtnNoFumador.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rbtnNoFumador.setText("No");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Email:");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Observacion:");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Genero");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Fecha Nacimiento:");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Estado Civil");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Desempleado");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("Fumador");

        txtAliasCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtapellidoCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Alias");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Apellido:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Direccion");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Poblacion:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Telefono:");

        jLabel44.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel44.setText("Cedula:");

        txtnombreCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtCedula.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtDireccionCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        ChckEditarCliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ChckEditarCliente.setText("Editar");
        ChckEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChckEditarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelefonoCliente)
                                    .addComponent(txtemailCliente)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel44)
                                .addGap(18, 18, 18)
                                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(11, 11, 11)
                                .addComponent(txtapellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAliasCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtnombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtPoblacionCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                                .addComponent(txtMovilCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtObservacionCliente, javax.swing.GroupLayout.Alignment.LEADING)))))))
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(46, 46, 46)
                                .addComponent(rbtnSiFumador, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(rbtnNoFumador, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbEstadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbSexoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ChckEditarCliente)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(rbtnSiDesempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(rbtnNoDesempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jdcFechaNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtAliasCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtapellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtnombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtPoblacionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtMovilCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtemailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtObservacionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(cbSexoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addComponent(jdcFechaNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(cbEstadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(rbtnSiDesempleado)
                        .addComponent(rbtnNoDesempleado)))
                .addGap(27, 27, 27)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(rbtnSiFumador)
                    .addComponent(rbtnNoFumador)
                    .addComponent(ChckEditarCliente))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        btnGuardarCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnGuardarCliente.setText("Guardar");
        btnGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarClienteActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnGuardarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addContainerGap(336, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(102, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(403, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarCliente)
                    .addComponent(jButton1))
                .addGap(25, 25, 25))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(62, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChckEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChckEditarClienteActionPerformed
        try {
            if (txtAliasCliente.getText().isEmpty() || txtapellidoCliente.getText().isEmpty() || txtDireccionCliente.getText().isEmpty() || txtnombreCliente.getText().isEmpty() || txtTelefonoCliente.getText().isEmpty() || txtMovilCliente.getText().isEmpty()
                    || txtemailCliente.getText().isEmpty() || txtObservacionCliente.getText().isEmpty() || cbEstadocivil.getSelectedItem().equals("Seleccione el estado civil")
                    || txtPoblacionCliente.getText().isEmpty() || ((JTextField) jdcFechaNacimientoCliente.getDateEditor().getUiComponent()).getText().isEmpty() || cbSexoCliente.getSelectedItem().equals("Seleccione el genero") || !rbtnNoDesempleado.isSelected() && !rbtnSiDesempleado.isSelected() || !rbtnNoFumador.isSelected() && !rbtnSiFumador.isSelected()) {
                JOptionPane.showMessageDialog(null, "Ingrese los campos");
            } else {
                int id = Integer.parseInt(txtCedula.getText());
                String alias = txtAliasCliente.getText();
                String nombre = txtnombreCliente.getText();
                String apellido = txtapellidoCliente.getText();
                String direccion = txtDireccionCliente.getText();
                String poblacion = txtPoblacionCliente.getText();
                String telefono = txtTelefonoCliente.getText();
                String movil = txtMovilCliente.getText();
                String email = txtemailCliente.getText();
                String observacion = txtObservacionCliente.getText();
                Date fechaNacimiento = jdcFechaNacimientoCliente.getDate();
                java.sql.Date fecha2 = new java.sql.Date(fechaNacimiento.getYear(), fechaNacimiento.getMonth(), fechaNacimiento.getDay());
                String genero = cbSexoCliente.getSelectedItem().toString();
                String estadocivil = cbEstadocivil.getSelectedItem().toString();
                boolean desempleado = ObtenerValorDesempleado();
                boolean fumador = false;
                if (rbtnSiFumador.isSelected()) {
                    fumador = true;
                } else if (rbtnNoFumador.isSelected()) {
                    fumador = false;
                }
                if (ctlCliente.SolicitudModificar(id, alias, nombre, apellido, direccion, poblacion, telefono, movil, email, observacion, fecha2, genero, estadocivil, desempleado, fumador)) {
                    if (validarEmail(email)) {
                        JOptionPane.showMessageDialog(this, "Editado exitosamente");
                        ChckEditarCliente.setEnabled(false);
                        listarClientes();
                        limpiarClientes();
                    } else {
                        JOptionPane.showMessageDialog(this, "Email invalido");
                        ChckEditarCliente.setSelected(false);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Error al editar");
                }

            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_ChckEditarClienteActionPerformed

    private void btnGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarClienteActionPerformed
        try {
            if (txtAliasCliente.getText().isEmpty() || txtapellidoCliente.getText().isEmpty() || txtDireccionCliente.getText().isEmpty() || txtnombreCliente.getText().isEmpty() || txtTelefonoCliente.getText().isEmpty() || txtMovilCliente.getText().isEmpty()
                    || txtemailCliente.getText().isEmpty() || txtObservacionCliente.getText().isEmpty() || cbEstadocivil.getSelectedItem().equals("Seleccione el estado civil")
                    || txtPoblacionCliente.getText().isEmpty() || ((JTextField) jdcFechaNacimientoCliente.getDateEditor().getUiComponent()).getText().isEmpty() || cbSexoCliente.getSelectedItem().equals("Seleccione el genero") || !rbtnNoDesempleado.isSelected() && !rbtnSiDesempleado.isSelected() || !rbtnNoFumador.isSelected() && !rbtnSiFumador.isSelected()) {
                JOptionPane.showMessageDialog(null, "Ingrese los campos");
            } else {
                int id = Integer.parseInt(txtCedula.getText());
                String alias = txtAliasCliente.getText();
                String nombre = txtnombreCliente.getText();
                String apellido = txtapellidoCliente.getText();
                String direccion = txtDireccionCliente.getText();
                String poblacion = txtPoblacionCliente.getText();
                String telefono = txtTelefonoCliente.getText();
                String movil = txtMovilCliente.getText();
                String email = txtemailCliente.getText();
                String observacion = txtObservacionCliente.getText();
                Date fechaNacimiento = jdcFechaNacimientoCliente.getDate();
                java.sql.Date fecha2 = new java.sql.Date(fechaNacimiento.getYear(), fechaNacimiento.getMonth(), fechaNacimiento.getDay());
                String genero = cbSexoCliente.getSelectedItem().toString();
                String estadocivil = cbEstadocivil.getSelectedItem().toString();
                boolean desempleado = ObtenerValorDesempleado();
                boolean fumador = false;
                if (rbtnSiFumador.isSelected()) {
                    fumador = true;
                } else if (rbtnNoFumador.isSelected()) {
                    fumador = false;
                }
                if (validarEmail(email)) {
                    if (ctlCliente.SolicitudGuardar(id, alias, nombre, apellido, direccion, poblacion, telefono, movil, email, observacion, fecha2, genero, estadocivil, desempleado, fumador)) {

                        JOptionPane.showMessageDialog(this, "Guardado exitosamente");
                        listarClientes();
                        limpiarClientes();
                    } else {
                        JOptionPane.showMessageDialog(this, "Error al guardar");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Correo invalido ingreselo de esta manera: 'Programador@gmail.com'");
                }

            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnGuardarClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ChckEditarCliente;
    private javax.swing.JButton btnGuardarCliente;
    private javax.swing.JComboBox<String> cbEstadocivil;
    private javax.swing.JComboBox<String> cbSexoCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel8;
    private com.toedter.calendar.JDateChooser jdcFechaNacimientoCliente;
    private javax.swing.JRadioButton rbtnNoDesempleado;
    private javax.swing.JRadioButton rbtnNoFumador;
    private javax.swing.JRadioButton rbtnSiDesempleado;
    private javax.swing.JRadioButton rbtnSiFumador;
    private javax.swing.JTextField txtAliasCliente;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDireccionCliente;
    private javax.swing.JTextField txtMovilCliente;
    private javax.swing.JTextField txtObservacionCliente;
    private javax.swing.JTextField txtPoblacionCliente;
    private javax.swing.JTextField txtTelefonoCliente;
    private javax.swing.JTextField txtapellidoCliente;
    private javax.swing.JTextField txtemailCliente;
    private javax.swing.JTextField txtnombreCliente;
    // End of variables declaration//GEN-END:variables

    public boolean ObtenerValorDesempleado() {
        boolean des = false;
        if (rbtnNoDesempleado.isSelected()) {
            des = false;
        } else if (rbtnSiDesempleado.isSelected()) {
            des = true;
        }
        return des;
    }
    
    public boolean validarEmail(String email) {
        Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        Matcher mather = pattern.matcher(email);
        return mather.matches();
    }
     private void listarClientes() {
        DB.tableClientes2.setModel(ctlCliente.SolicitudListar());
    }
     public void limpiarClientes() {
        txtCedula.setText("");
        txtapellidoCliente.setText("");
        txtDireccionCliente.setText("");
        txtTelefonoCliente.setText("");
        txtemailCliente.setText("");
        cbSexoCliente.setSelectedIndex(-1);
        cbEstadocivil.setSelectedIndex(-1);
        txtAliasCliente.setText("");
        txtnombreCliente.setText("");
        txtPoblacionCliente.setText("");
        txtMovilCliente.setText("");
        txtObservacionCliente.setText("");
        jdcFechaNacimientoCliente.setDate(null);
        rbtnSiDesempleado.setSelected(false);
        rbtnNoDesempleado.setSelected(false);
        rbtnSiFumador.setSelected(false);
        rbtnNoFumador.setSelected(false);
        ChckEditarCliente.setSelected(false);
    }
     

}

